"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['iOSTool.py']
DATA_FILES = ["./libimobiledevice-macosx/"]
OPTIONS = {
    'argv_emulation': False,
    'iconfile': './iOSTool.icns',
    'plist': {'CFBundleShortVersionString': '0.1.0', }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
